# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77d82ea9fc16d327575af4235c4f44a13b2dfe94a4509721ee21be8ca5bd44b17841c5264b779bb7dd17e3c3423ce1703ab646173311723e8e48f80c2bd84218

test:
  secret_key_base: 2ba7bd547162d4e29321e377c95de7a3603f5fff2449dc8a1a51fc070364b5d08822772a63e4d0624f774098409a9f5b485ba7a8abcafe30ba49570aa17ff508

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
